### ISSUE TITLE
Error with Embeddings 

### ISSUE THREAD

**Issue by yongzx** [akb89/pyfn#13]
When I run `./frameid.sh -m train -x 101` after conversion and preprocessing with 
`./preprocess.sh -x 101 -t nlp4j -d bmst -p semafor`
I encounter this error:
```
Preparing files for frame identification...
Converting to .flattened format for the SEMAFOR parser...
Processing file: /home/zxy485/zxy485gallinahome/week1/pyfn/scripts/../experiments/xp_101/frameid/data/corpora/test.sentences.conllx
Done
Training frame identification on all models...
Using TensorFlow backend.
['/home/zxy485/zxy485gallinahome/week1/pyfn/scripts/../lib/eacl2017-oodFrameNetSRL/simpleFrameId/main.py', 'train', '/home/zxy485/zxy485gallinahome/week1/pyfn/scripts/../experiments/xp_101/frameid']
Traceback (most recent call last):
  File "/home/zxy485/zxy485gallinahome/week1/pyfn/scripts/../lib/eacl2017-oodFrameNetSRL/simpleFrameId/main.py", line 186, in <module>
    EMBEDDINGS_NAME = sys.argv[3]
IndexError: list index out of range
Done
```
It seems like the embedding file is missing. May I know where to seek for the embedding file? Thank you!

**Comment by akb89** [comment]
Thanks for reporting this! I recently added two new scripts (`frameid.embed.sh`and `open-sesame.embed.sh`) to be able to specify which embeddings to use is both frame and argument identification and I forgot to update the `frameid.sh` script accordingly, which introduced a bug. 
It's now fixed, you can download the updated scripts via:
```
wget http://129.194.21.122/~kabbach/pyfn/scripts.7z
```
or directly on Github by downloading files under `https://github.com/akb89/pyfn/tree/master/scripts`. 
I have also updated the README to add the specific package versions required by SIMPLEFRAMEID, as I realized it no longer worked when installing the latest dependencies. You can install them via:
```
pip install keras==2.0.6 lightfm==1.13 sklearn numpy==1.13.1 networkx==1.11 tensorflow==1.3.0
```
before running: 
```
./frameid.sh -m train -x 101
```

**Comment by yongzx** [comment]
Thank you so much for the reply!
I now run into a new error, but I am unsure what's the main cause of it. Is it because my data file is corrupted as the error is `ValueError: need at least one array to concatenate`?
```
$ module load python/3.6.6
$ pyfn convert \
  --from fnxml \
  --to semafor \
  --source /path/to/fndata-1.7-with-dev \
  --target /path/to/experiments/xp_101/data \
  --splits train \
  --output_sentences
$ ./preprocess.sh -x 101 -t nlp4j -d bmst -p semafor  # no error
$ ./prepare.sh -x 101 -p semafor -s test -f /home/zxy485/zxy485gallinahome/week1-4/pyfn/data/fndata-1.7-with-dev  # no error
$ module load python2/2.7.13
$ ./frameid.sh -m train -x 101
Preparing files for frame identification...
Converting to .flattened format for the SEMAFOR parser...
Processing file: /home/zxy485/zxy485gallinahome/week1-4/pyfn/scripts/../experiments/xp_101/frameid/data/corpora/test.sentences.conllx
Done
Training frame identification on all models...
Using TensorFlow backend.
train
Starting resource manager
Initializing reporters
Running the experiments!
12 configurations,  1  train-test pairs ->  12  runs
Malformed parse data in sentence 0
Malformed parse data in sentence 1
Malformed parse data in sentence 2
Malformed parse data in sentence 3
Malformed parse data in sentence 4
Malformed parse data in sentence 5
Malformed parse data in sentence 6
Malformed parse data in sentence 7
Malformed parse data in sentence 8
Malformed parse data in sentence 9
Malformed parse data in sentence 10
Malformed parse data in sentence 11
Malformed parse data in sentence 12
Malformed parse data in sentence 13
Malformed parse data in sentence 14
Malformed parse data in sentence 15
Malformed parse data in sentence 16
Malformed parse data in sentence 17
Malformed parse data in sentence 18
Malformed parse data in sentence 19
Malformed parse data in sentence 20
Malformed parse data in sentence 21
Malformed parse data in sentence 22
Malformed parse data in sentence 23
Malformed parse data in sentence 24
Malformed parse data in sentence 25
Malformed parse data in sentence 26
Malformed parse data in sentence 27
Malformed parse data in sentence 28
Malformed parse data in sentence 29
Malformed parse data in sentence 30
Malformed parse data in sentence 31
Malformed parse data in sentence 32
Malformed parse data in sentence 33
Malformed parse data in sentence 34
Malformed parse data in sentence 35
Malformed parse data in sentence 36
Malformed parse data in sentence 37
Malformed parse data in sentence 38
Malformed parse data in sentence 39
Malformed parse data in sentence 40
Malformed parse data in sentence 41
Malformed parse data in sentence 42
Malformed parse data in sentence 43
Malformed parse data in sentence 44
Malformed parse data in sentence 45
Malformed parse data in sentence 46
Malformed parse data in sentence 47
Malformed parse data in sentence 48
Malformed parse data in sentence 49
Malformed parse data in sentence 50
Malformed parse data in sentence 51
Malformed parse data in sentence 52
Malformed parse data in sentence 53
Malformed parse data in sentence 54
Malformed parse data in sentence 55
Malformed parse data in sentence 56
Malformed parse data in sentence 57
Malformed parse data in sentence 58
Malformed parse data in sentence 59
Malformed parse data in sentence 60
Malformed parse data in sentence 61
Malformed parse data in sentence 62
Malformed parse data in sentence 63
Malformed parse data in sentence 64
Malformed parse data in sentence 65
Malformed parse data in sentence 66
Malformed parse data in sentence 67
Malformed parse data in sentence 68
Malformed parse data in sentence 69
Malformed parse data in sentence 70
Malformed parse data in sentence 71
Malformed parse data in sentence 72
Malformed parse data in sentence 73
Malformed parse data in sentence 74
train.sentences.conllx.flattened train.frame.elements labeled: 3362 parsed: 75 graphs: 0
Traceback (most recent call last):
  File "/home/zxy485/zxy485gallinahome/week1-4/pyfn/scripts/../lib/eacl2017-oodFrameNetSRL/simpleFrameId/main.py", line 188, in <module>
    _train_all(HOME, EMBEDDINGS_NAME)
  File "/home/zxy485/zxy485gallinahome/week1-4/pyfn/scripts/../lib/eacl2017-oodFrameNetSRL/simpleFrameId/main.py", line 138, in _train_all
    X_train, y_train, lemmapos_train, gid_train = mapper.get_matrix(g_train)
  File "/mnt/rds/redhen/gallina/home/zxy485/week1-4/pyfn/lib/eacl2017-oodFrameNetSRL/simpleFrameId/representation.py", line 29, in get_matrix
    X = np.vstack(X)
  File "/home/zxy485/.local/lib/python2.7/site-packages/numpy/core/shape_base.py", line 237, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate
Done
```
