### ISSUE TITLE
frameid.sh - ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by yongzx** [akb89/pyfn#16]
Thank you so much for the reply #13 !
I now run into a new error, but I am unsure what's the main cause of it. Is it because my data file is corrupted as the error is `ValueError: need at least one array to concatenate`?
```
$ module load python/3.6.6
$ pyfn convert \
  --from fnxml \
  --to semafor \
  --source /path/to/fndata-1.7-with-dev \
  --target /path/to/experiments/xp_101/data \
  --splits train \
  --output_sentences
$ ./preprocess.sh -x 101 -t nlp4j -d bmst -p semafor  # no error
$ ./prepare.sh -x 101 -p semafor -s test -f /home/zxy485/zxy485gallinahome/week1-4/pyfn/data/fndata-1.7-with-dev  # no error
$ module load python2/2.7.13
$ ./frameid.sh -m train -x 101
Preparing files for frame identification...
Converting to .flattened format for the SEMAFOR parser...
Processing file: /home/zxy485/zxy485gallinahome/week1-4/pyfn/scripts/../experiments/xp_101/frameid/data/corpora/test.sentences.conllx
Done
Training frame identification on all models...
Using TensorFlow backend.
train
Starting resource manager
Initializing reporters
Running the experiments!
12 configurations,  1  train-test pairs ->  12  runs
Malformed parse data in sentence 0
Malformed parse data in sentence 1
Malformed parse data in sentence 2
Malformed parse data in sentence 3
Malformed parse data in sentence 4
Malformed parse data in sentence 5
Malformed parse data in sentence 6
Malformed parse data in sentence 7
Malformed parse data in sentence 8
Malformed parse data in sentence 9
Malformed parse data in sentence 10
Malformed parse data in sentence 11
Malformed parse data in sentence 12
Malformed parse data in sentence 13
Malformed parse data in sentence 14
Malformed parse data in sentence 15
Malformed parse data in sentence 16
Malformed parse data in sentence 17
Malformed parse data in sentence 18
Malformed parse data in sentence 19
Malformed parse data in sentence 20
Malformed parse data in sentence 21
Malformed parse data in sentence 22
Malformed parse data in sentence 23
Malformed parse data in sentence 24
Malformed parse data in sentence 25
Malformed parse data in sentence 26
Malformed parse data in sentence 27
Malformed parse data in sentence 28
Malformed parse data in sentence 29
Malformed parse data in sentence 30
Malformed parse data in sentence 31
Malformed parse data in sentence 32
Malformed parse data in sentence 33
Malformed parse data in sentence 34
Malformed parse data in sentence 35
Malformed parse data in sentence 36
Malformed parse data in sentence 37
Malformed parse data in sentence 38
Malformed parse data in sentence 39
Malformed parse data in sentence 40
Malformed parse data in sentence 41
Malformed parse data in sentence 42
Malformed parse data in sentence 43
Malformed parse data in sentence 44
Malformed parse data in sentence 45
Malformed parse data in sentence 46
Malformed parse data in sentence 47
Malformed parse data in sentence 48
Malformed parse data in sentence 49
Malformed parse data in sentence 50
Malformed parse data in sentence 51
Malformed parse data in sentence 52
Malformed parse data in sentence 53
Malformed parse data in sentence 54
Malformed parse data in sentence 55
Malformed parse data in sentence 56
Malformed parse data in sentence 57
Malformed parse data in sentence 58
Malformed parse data in sentence 59
Malformed parse data in sentence 60
Malformed parse data in sentence 61
Malformed parse data in sentence 62
Malformed parse data in sentence 63
Malformed parse data in sentence 64
Malformed parse data in sentence 65
Malformed parse data in sentence 66
Malformed parse data in sentence 67
Malformed parse data in sentence 68
Malformed parse data in sentence 69
Malformed parse data in sentence 70
Malformed parse data in sentence 71
Malformed parse data in sentence 72
Malformed parse data in sentence 73
Malformed parse data in sentence 74
train.sentences.conllx.flattened train.frame.elements labeled: 3362 parsed: 75 graphs: 0
Traceback (most recent call last):
  File "/home/zxy485/zxy485gallinahome/week1-4/pyfn/scripts/../lib/eacl2017-oodFrameNetSRL/simpleFrameId/main.py", line 188, in <module>
    _train_all(HOME, EMBEDDINGS_NAME)
  File "/home/zxy485/zxy485gallinahome/week1-4/pyfn/scripts/../lib/eacl2017-oodFrameNetSRL/simpleFrameId/main.py", line 138, in _train_all
    X_train, y_train, lemmapos_train, gid_train = mapper.get_matrix(g_train)
  File "/mnt/rds/redhen/gallina/home/zxy485/week1-4/pyfn/lib/eacl2017-oodFrameNetSRL/simpleFrameId/representation.py", line 29, in get_matrix
    X = np.vstack(X)
  File "/home/zxy485/.local/lib/python2.7/site-packages/numpy/core/shape_base.py", line 237, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate
Done
```

**Comment by akb89** [comment]
Ah, I remember having this issue when I was using the wrong dependency versions for SIMPLEFRAMEID. FYI, those should work (I have updated the pyfn README accordingly):
```
pip install keras==2.0.6 lightfm==1.13 sklearn numpy==1.13.1 networkx==1.11 tensorflow==1.3.0
```
1. Could you check your above dependency versions (on python 2.7), update them if necessary before re-running `./frameid.sh -m train -x 101` and let me know if it works?
2. If not, could you copy-past here a few lines of the `train.sentences.conllx.flattened` and `train.frame.elements` files found under xp_101/frameid/data/corpora to see if they're well-formed? 
Thanks in advance

**Comment by yongzx** [comment]
> Could you check your above dependency versions (on python 2.7), update them if necessary before re-running ./frameid.sh -m train -x 101 and let me know if it works?
Yeap. I have already updated it and still continue seeing the error.


> If not, could you copy-past here a few lines of the train.sentences.conllx.flattened and train.frame.elements files found under xp_101/frameid/data/corpora to see if they're well-formed?
This is the few lines from `train.frame.elements`.
```
1	0.0	3	Possession	have.v	3	have	3357	Owner	1	Possession	4:13
1	0.0	3	Competition	competitor.n	6	competitors	3357	Participants	6	Competition	7:9
1	0.0	4	Theft	steal.v	7	stealing	3357	Perpetrator	4:6	Goods	8:9	Victim	8
1	0.0	3	Temporal_collocation	at.prep	10	at	3357	Landmark_period	11:13	Trajector_event	4:9
1	0.0	3	Identicality	same.a	12	same	3357	Type	13	Current_instance	12:13
1	0.0	3	Capability	can.v	2	can	3357	Entity	1	Event	3:13
1	0.0	3	Statement	say.v	19	said	3357	Speaker	16:18	Message	0:15
1	0.0	2	Duration_description	brief.a	1	brief	3358	Eventuality	2
1	0.0	2	History	history.n	2	History	3358	Duration	1
1	0.0	2	Leadership	president [political].n	2	President	3359	Leader	2
1	0.0	3	People	people.n	4	people	3360	Person	4	Context_of_acquaintance	5:7
1	0.0	3	Possession	have.v	4	have	3361	Owner	3	Possession	5:14
1	0.0	5	Desirability	good.a	10	better	3361	Comparison_set	12:14	Circumstances	3:6	Circumstances	7	Degree	9
```

This below is a few lines from `train.sentences.conllx.flattened`
```
3	a	brief	History	DT	JJ	NN	_	_	_	_	_	_	O	O	O	a	brief	history
8	speaker20	:	President	I	second	the	motion	.	NN	:	NNP	PRP	VBP	DT	NN	.	_	_	_	_	__	_	_	_	_	_	_	_	_	_	_	O	O	O	O	O	O	O	O	speaker0	:	president	I	#ord#	the	motion	.
10	welcome	back	to	``	people	in	the	news	.	''	JJ	RB	TO	``	NNS	IN	DT	NN	.	''	_	_	__	_	_	_	_	_	_	_	_	_	_	_	_	_	_	_	_	O	O	O	O	O	O	OO	O	O	welcome	back	to	``	people	in	the	news	.	''
17	yesterday	:	``	We	have	a	situation	that	is	noticeably	better	than	in	recent	days	.	''	NN	:	``	PRP	VBP	DT	NN	WDT	VBZ	RB	JJR	IN	IN	JJ	NNS	.	''	_	_	_	_	_	_	_	_	__	_	_	_	_	_	_	_	_	_	_	_	_	_	_	_	_	_	_	_	_	_	_	__	O	O	O	O	O	O	O	O	O	O	O	O	O	O	O	O	O	yesterday	:	``	wehave	a	situation	that	be	noticeably	good	than	in	recent	day	.	''
```

**Comment by akb89** [comment]
Ok so your problem is clearly related to the `train.sentences.conllx.flattened` file generate by the command `./preprocess.sh -x 101 -t nlp4j -d bmst -p semafor`. FYI, the output file should look like this:
```
[...]
3	A	Brief	History	DT	JJ	NN	det	amod	root	3	3	0	O	O	O	a	brief	history
[...]
8	speaker20	:	President	I	second	the	motion	.	NN	:	NNP	PRP	VBP	DT	NN	.	root	punct	nn	nsubj	dep	det	dobj	punct	0	1	4	5	1	7	5	1	O	O	O	O	O	O	O	O	speaker0	:	president	I	#ord#	the	motion	.
[...]
```
It looks like the BMST parser did not work. 
It is possible that the command actually generated errors (it's not always obvious from the console and it will move on even with errors, making it look like everything went fine when it actually did not). 
Could you check out the console output of `./preprocess.sh -x 101 -t nlp4j -d bmst -p semafor` step-by-step and let me know if you spot an error? 
FYI also you should have an intermediate file `train.sentences.conllx` that looks like this:
```
[...]
1	A	a	DT	DT	_	3	det	_	_
2	Brief	brief	JJ	JJ	_	3	amod	_	_
3	History	history	NN	NN	_	0	root	_	_
[...]
1	speaker20	speaker0	NN	NN	_	0	root	_	_
2	:	:	:	:	_	1	punct	_	_
3	President	president	NNP	NNP	_	4	nn	_	_
4	I	I	PRP	PRP	_	5	nsubj	_	_
5	second	#ord#	VBP	VBP	_	1	dep	_	_
6	the	the	DT	DT	_	7	det	_	_
7	motion	motion	NN	NN	_	5	dobj	_	_
8	.	.	.	.	_	1	punct	_	_
[...]
```

**Comment by yongzx** [comment]
I decided to redo everything and store them in `xp_103` and put the console outputs here. The error that you mention is `rm: cannot remove ‘/home/zxy485/zxy485gallinahome/week1-4/pyfn/scripts/../experiments/xp_103/data/test_pred.conll.txt’`. Initially, I thought that's normal since I am splitting on `train`. May I know what causes the error here? Thank you very much! 
```
$ pyfn convert \
>   --from fnxml \
>   --to semafor \
>   --source /home/zxy485/zxy485gallinahome/week1-4/pyfn/data/fndata-1.7-with-dev \
>   --target /home/zxy485/zxy485gallinahome/week1-4/pyfn/experiments/xp_103/data \
>   --splits train \
>   --output_sentences
INFO - Marshalling test splits to semafor format
INFO - Marshalling test splits to semafor format
INFO - Marshalling test splits to semafor format
INFO - Marshalling dev splits to semafor format
INFO - Marshalling dev splits to semafor format
INFO - Marshalling dev splits to semafor format
INFO - Marshalling train splits to semafor format
INFO - Marshalling train splits to semafor format
INFO - Marshalling train splits to semafor format

$ ./preprocess.sh -x 103 -t nlp4j -d bmst -p semafor
Initializing preprocessing...
Preprocessing setup:
  XP_DIR: /home/zxy485/zxy485gallinahome/week1-4/pyfn/scripts/../experiments/xp_103
  POS tagger: nlp4j
  Dependency parser: bmst
  Frame semantic parser: semafor
Initializing part-of-speech tagging...
POS tagging via NLP4J...
Processing file: /home/zxy485/zxy485gallinahome/week1-4/pyfn/scripts/../experiments/xp_103/data/test.sentences
Masking _ chars...
Done
Brownifying...
Done
Unmasking _ chars...
Done
Converting .sentences to .tsv format...
Done
POS tagging tsv file...
Processing file: /home/zxy485/zxy485gallinahome/week1-4/pyfn/scripts/../experiments/xp_103/data/test.sentences.tsv
Done
Converting .nlp4j to .conllx format...
Processing file: /home/zxy485/zxy485gallinahome/week1-4/pyfn/scripts/../experiments/xp_103/data/test.sentences.tsv.nlp4j
Done
Initializing part-of-speech tagging...
POS tagging via NLP4J...
Processing file: /home/zxy485/zxy485gallinahome/week1-4/pyfn/scripts/../experiments/xp_103/data/train.sentences
Masking _ chars...
Done
Brownifying...
Done
Unmasking _ chars...
Done
Converting .sentences to .tsv format...
Done
POS tagging tsv file...
Processing file: /home/zxy485/zxy485gallinahome/week1-4/pyfn/scripts/../experiments/xp_103/data/train.sentences.tsv
Done
Converting .nlp4j to .conllx format...
Processing file: /home/zxy485/zxy485gallinahome/week1-4/pyfn/scripts/../experiments/xp_103/data/train.sentences.tsv.nlp4j
Done
Initializing dependency parsing...
Dependency-parsing via BIST MST parser...
Processing file: /home/zxy485/zxy485gallinahome/week1-4/pyfn/scripts/../experiments/xp_103/data/test.sentences.conllx
rm: cannot remove ‘/home/zxy485/zxy485gallinahome/week1-4/pyfn/scripts/../experiments/xp_103/data/test_pred.conll.txt’: No such file or directory
mv: cannot stat ‘/home/zxy485/zxy485gallinahome/week1-4/pyfn/scripts/../experiments/xp_103/data/test_pred.conll’: No such file or directory
Done
Initializing dependency parsing...
Dependency-parsing via BIST MST parser...
Processing file: /home/zxy485/zxy485gallinahome/week1-4/pyfn/scripts/../experiments/xp_103/data/train.sentences.conllx
rm: cannot remove ‘/home/zxy485/zxy485gallinahome/week1-4/pyfn/scripts/../experiments/xp_103/data/test_pred.conll.txt’: No such file or directory
mv: cannot stat ‘/home/zxy485/zxy485gallinahome/week1-4/pyfn/scripts/../experiments/xp_103/data/test_pred.conll’: No such file or directory
Done
Converting to .flattened format for the SEMAFOR parser...
Processing file: /home/zxy485/zxy485gallinahome/week1-4/pyfn/scripts/../experiments/xp_103/data/train.sentences.conllx
``` 

Apparently my `train.sentences.conllx` also doesn't look the same (two columns are missing). 
```
1	yesterday	yesterday	NN	NN	_	_	_	_	_
2	:	:	:	:	_	_	_	_	_
3	``	``	``	``	_	_	_	_	_
4	We	we	PRP	PRP	_	_	_	_	_
5	have	have	VBP	VBP	_	_	_	_	_
6	a	a	DT	DT	_	_	_	_	_
7	situation	situation	NN	NN	_	_	_	_	_
8	that	that	WDT	WDT	_	_	_	_	_
9	is	be	VBZ	VBZ	_	_	_	_	_
10	noticeably	noticeably	RB	RB	_	_	_	_	_
11	better	good	JJR	JJR	_	_	_	_	_
12	than	than	IN	IN	_	_	_	_	_
13	in	in	IN	IN	_	_	_	_	_
14	recent	recent	JJ	JJ	_	_	_	_	_
15	days	day	NNS	NNS	_	_	_	_	_
16	.	.	.	.	_	_	_	_	_
17	''	''	''	''	_	_	_	_	_
```

**Comment by akb89** [comment]
Ok so the problem actually arises with dependency parsing with the BIST parser at `Initializing dependency parsing...`. Have you installed DyNET on python 2.7? The BIST parser needs it. As per the README of pyfn, you need to install `https://dynet.readthedocs.io/en/2.0.2/python.html`. 

FYI, to check whether DyNET is properly installed and functional on python2.7, you can type in:
```
import dynet
```
in the python console and you should see:
```
Python 2.7.16 (default, Apr 12 2019, 15:32:40)
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dynet
[dynet] random seed: 4255027741
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
```
Let me know if that solves your problem.

**Comment by yongzx** [comment]
Thank you!! The frameid.sh is running now!

The problem of frameid.sh not working is due to DyNET not properly installed. It must be installed on python2.7 via `pip install dynet==2.0.2` (I explicitly mention here because the guide linked in the README presents a more challenging installing process).

**Comment by akb89** [comment]
Ok thanks! I remember experiencing problems when installing dynet via pip, but I can update the README to include both possibilities, since installing via pip is indeed simpler.
