### ISSUE TITLE
pyfn convert crashes because it cannot find logging.yml

### ISSUE THREAD

**Issue by jcklie** [akb89/pyfn#2]
Steps to reproduce:

1, Create a virtual environment (I used 3.6 with no site packages)
2. Install pyfn via pip
3. Run `pyfn convert,` I think that the command line arguments do not matter, it crashes before doing anything.

```
pyfn convert --from fnxml --to semeval --source XXX --target XXX --splits {train,dev,test}
Traceback (most recent call last):
  File "/home/jck/git/XXXY/venv/bin/pyfn", line 7, in <module>
    from pyfn.main import main
  File "/home/jck/git/XXXY/venv/lib/python3.6/site-packages/pyfn/main.py", line 27, in <module>
    os.path.join(os.path.dirname(__file__), 'logging', 'logging.yml')))
  File "/home/jck/git/XXXY/venv/lib/python3.6/site-packages/pyfn/utils/config.py", line 19, in load
    with open(config_file, 'r') as config_stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jck/git/XXXY/venv/lib/python3.6/site-packages/pyfn/logging/logging.yml'
```

**Comment by akb89** [comment]
Fixed in v1.1.1. Thanks for the report!
